# Step 1: Use an official OpenJDK runtime as the base image
FROM eclipse-temurin:21-alpine

EXPOSE 8080
ARG JAR_FILE=target/preExam-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]