apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shopping-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: <your-frontend-image>:latest # Replace with your image name
        ports:
        - containerPort: 8000
        env:
        - name: BACKEND_URL
          value: "http://backend:8080/api/shopping"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: shopping-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer