version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8000:8000"
    environment:
      - BACKEND_URL=http://backend:8080/api/shopping
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"