-- create table
CREATE TABLE shopping_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    amount INTEGER NOT NULL,                                
    name CHARACTER VARYING(255) NOT NULL                   
);

-- insert data
INSERT INTO shopping_item (amount, name) VALUES (100, 'apple');
INSERT INTO shopping_item (amount, name) VALUES (20, 'banana');
INSERT INTO shopping_item (amount, name) VALUES (341, 'cherry');